// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Dokhoyan/go-messenger-microservices/user_service/internal/service (interfaces: AuthDataService)
//
// Generated by this command:
//
//	mockgen -destination=../service/mocks/authdata_service.go -package=mocks . AuthDataService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Dokhoyan/go-messenger-microservices/user_service/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthDataService is a mock of AuthDataService interface.
type MockAuthDataService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthDataServiceMockRecorder
	isgomock struct{}
}

// MockAuthDataServiceMockRecorder is the mock recorder for MockAuthDataService.
type MockAuthDataServiceMockRecorder struct {
	mock *MockAuthDataService
}

// NewMockAuthDataService creates a new mock instance.
func NewMockAuthDataService(ctrl *gomock.Controller) *MockAuthDataService {
	mock := &MockAuthDataService{ctrl: ctrl}
	mock.recorder = &MockAuthDataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthDataService) EXPECT() *MockAuthDataServiceMockRecorder {
	return m.recorder
}

// GetUserByUsername mocks base method.
func (m *MockAuthDataService) GetUserByUsername(ctx context.Context, username string) (*model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByUsername", ctx, username)
	ret0, _ := ret[0].(*model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByUsername indicates an expected call of GetUserByUsername.
func (mr *MockAuthDataServiceMockRecorder) GetUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByUsername", reflect.TypeOf((*MockAuthDataService)(nil).GetUserByUsername), ctx, username)
}
