version: '3.9'

volumes:
  postgres_volume:

services:
  pg:
    image: postgres
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  auth-service:
    build:
      context: ./auth_service
      dockerfile: docker/Dockerfile
    container_name: auth-service
    ports:
      - "8001:8080"
    networks:
      - messenger-net

  user-service:
    build:
      context: ./user_service
      dockerfile: docker/Dockerfile
    container_name: user-service
    ports:
      - "8002:8080"
    networks:
      - messenger-net
  chat-service:
    build:
      context: ./chat_service
      dockerfile: docker/Dockerfile
    container_name: chat-service
    ports:
      - "8003:8080"
    networks:
      - messenger-net
  subscriber-service:
    build:
      context: ./subscriber_service
      dockerfile: docker/Dockerfile
    container_name: subscriber-service
    ports:
      - "8004:8080"
    networks:
      - messenger-net
  


networks:
  messenger-net:
    driver: bridge
