// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Dokhoyan/go-messenger-microservices/user_service/internal/repository (interfaces: LogsRepository)
//
// Generated by this command:
//
//	mockgen -destination=../repository/mocks/logs_repository.go -package=mocks . LogsRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/Dokhoyan/go-messenger-microservices/user_service/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockLogsRepository is a mock of LogsRepository interface.
type MockLogsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLogsRepositoryMockRecorder
	isgomock struct{}
}

// MockLogsRepositoryMockRecorder is the mock recorder for MockLogsRepository.
type MockLogsRepositoryMockRecorder struct {
	mock *MockLogsRepository
}

// NewMockLogsRepository creates a new mock instance.
func NewMockLogsRepository(ctrl *gomock.Controller) *MockLogsRepository {
	mock := &MockLogsRepository{ctrl: ctrl}
	mock.recorder = &MockLogsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogsRepository) EXPECT() *MockLogsRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLogsRepository) Create(ctx context.Context, log model.Log) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, log)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockLogsRepositoryMockRecorder) Create(ctx, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLogsRepository)(nil).Create), ctx, log)
}

// Get mocks base method.
func (m *MockLogsRepository) Get(ctx context.Context, id int64) (model.Log, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(model.Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockLogsRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockLogsRepository)(nil).Get), ctx, id)
}
