// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MakeFriendRequest make friend request
//
// swagger:model MakeFriendRequest
type MakeFriendRequest struct {

	// from user id
	// Required: true
	FromUserID *int64 `json:"from_user_id"`

	// to user id
	// Required: true
	ToUserID *int64 `json:"to_user_id"`
}

// Validate validates this make friend request
func (m *MakeFriendRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFromUserID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateToUserID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MakeFriendRequest) validateFromUserID(formats strfmt.Registry) error {

	if err := validate.Required("from_user_id", "body", m.FromUserID); err != nil {
		return err
	}

	return nil
}

func (m *MakeFriendRequest) validateToUserID(formats strfmt.Registry) error {

	if err := validate.Required("to_user_id", "body", m.ToUserID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this make friend request based on context it is used
func (m *MakeFriendRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MakeFriendRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MakeFriendRequest) UnmarshalBinary(b []byte) error {
	var res MakeFriendRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
