syntax = "proto3";

package user_v1;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";
import "validate/validate.proto";
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";

option go_package = "github.com/Dokhoyan/go-messenger-microservices/user_service/pkg/api/user_v1;user_v1";

option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_swagger) = {
  info: {
    title: "Note API"
    version: "1.0.0"
    contact: {
      name: "Dokhoyan dev."
      email: "dokhoyanjobb@mail.ru"
    };
  };

  host: "localhost:8080",
  schemes: HTTP,
  schemes: HTTPS,
  consumes: "application/json",
  produces: "application/json",
};

service UserV1 {
    // Создает нового пользователя в системе
    rpc Create(CreateRequest) returns (CreateResponse) {
        option (google.api.http) = {
            post: "/user/v1/create"
            body: "*"
        };
    }

    // Возвращает пользователя по id
    rpc Get(GetRequest) returns (GetResponse) {
        option (google.api.http) = {
            get: "/user/v1/{id}"
        };
    }
}

message UserInfo {
    // Имя пользователя
    string name = 1 [(validate.rules).string = {min_len: 1, max_len: 50}];

    // Имя учетной записи
    string username = 2 [(validate.rules).string = {min_len: 1, max_len: 50}];

    // Почта пользователя
    string email = 3;

    // Дата рождения пользователя
    google.protobuf.Timestamp birth_date = 4 [(validate.rules).timestamp = {
        required: true;
        gt: {};
    }];

    string avatar_url = 5;
}

message User {
    // Идентификатор пользователя
    int64 id = 1;

    // Данные пользователя
    UserInfo info = 2;

    // Дата создания пользователя
    google.protobuf.Timestamp created_at = 3;

    // Дата обновления пользователя
    google.protobuf.Timestamp updated_at = 4;
}

message CreateRequest {
    UserInfo info = 1;
}

message CreateResponse {
    // Идентификатор созданного пользователя
    int64 id = 1;
}

message GetRequest {
    int64 id = 1;
}

message GetResponse {
    User user = 1;
}

message UpdateRequest {
    // Идентификатор обновляемого пользователя
    int64 id = 1;

    UpdateInfo info = 2;
}

message UpdateInfo {
    // Новое имя пользователя
    google.protobuf.StringValue name = 1;

    // Имя учетной записи
    google.protobuf.StringValue username = 2;

    // Новая почта пользователя
    google.protobuf.StringValue email = 3;

    // Дата рождения пользователя
    google.protobuf.Timestamp birth_date = 4;

    // Фото профиля
    google.protobuf.StringValue avatar_url = 5;
}

message DeleteRequest {
    // Идентификатор удаляемого пользователя
    int64 id = 1;
}

message GetUsersResponse {
    repeated User users = 1;
}


