linter:
  name: lint
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: '1.24.1'
        cache: false

    - name: golangci-lint (auth-service)
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.53
        working-directory: auth_service
        args: --timeout=30m --config=../../.golangci.pipeline.yaml

    - name: golangci-lint (user-service)
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.53
        working-directory: user_service
        args: --timeout=30m --config=../../.golangci.pipeline.yaml

    - name: golangci-lint (chat-service)
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.53
        working-directory: chat_service
        args: --timeout=30m --config=../../.golangci.pipeline.yaml

    - name: golangci-lint (storage-service)
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.53
        working-directory: storage_service
        args: --timeout=30m --config=../../.golangci.pipeline.yaml
